INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10001, 'Eleri', 'Learn Spring', CURRENT_DATE, 0);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10002, 'Eleri', 'Learn Spring Security', CURRENT_DATE, 0);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10003, 'Eleri', 'Learn Java', CURRENT_DATE, 0);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10004, 'Eleri', 'Learn Angular', CURRENT_DATE, 0);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10005, 'Eleri', 'Finish final project', CURRENT_DATE, 0);